/** Gameplay tuning. Distances are Three.js world units. */
export const GAME_CONFIG = {
  destination: { z: -1800, radius: 13, name: "MOM" },
  battery: {
    start: 1,
    drainPerSecond: 0.0075,
    boostExtraDrainPerSecond: 0.005,
  },
  movement: {
    cruiseSpeed: 13.5,
    accelerateSpeed: 16.5,
    brakeSpeed: 7,
    boostSpeed: 22.5,
    speedResponse: 3.8,
    lateralSpeed: 10,
    lateralResponse: 12,
    releaseResponse: 22,
    lateralLimit: 15,
    verticalSpeed: 7,
    verticalResponse: 12,
    minAltitude: -7,
    maxAltitude: 12,
    collisionRadius: 0.65,
    bankAmount: 0.18,
  },
  camera: { baseFov: 70, boostFov: 79, followResponse: 6, lookAhead: 28 },
  nitro: {
    idleJetLength: 1.25,
    boostJetLength: 4.7,
    shockRingsPerEngine: 4,
    streakCount: 24,
    streakLength: 3.4,
    streakTravel: 48,
    idleLight: 14,
    boostLight: 42,
  },
  world: {
    fogDensity: 0.00078,
    fixtureLightIntensity: 1050,
    fixtureLightDistance: 84,
    bloomStrength: 0.3,
    bloomMaxHeight: 240,
  },
  scan: { cooldown: 5 },
  course: { splitZ: -740, splitStart: -640, splitEnd: -860, visibleAhead: 260 },
  obstacles: {
    damageBattery: 0.025,
    damagePrivacy: 9,
    rotorSpeed: 0.26,
    rotorHalfWidth: 1.3,
  },
  guidance: {
    visibleAhead: 155,
    directionDeadzone: 1.4,
    rotorAimRadius: 8,
    trackerMargin: 3,
    points: 40,
  },
  scoring: { targetSeconds: 160, fastSeconds: 110, timeMultiplier: 50 },
  nodes: {
    trackerPrivacyDamage: 12,
    trackerBatteryDamage: 0.025,
    nearMissMargin: 4.2,
    boosterCharge: 0.07,
    publicPrivacyDamage: 12,
    relayBurstSpeed: 2,
    relayBurstSeconds: 1.25,
    boosterBurstSeconds: 1.8,
    publicBurstSpeed: 5,
    publicBurstSeconds: 7,
    tipComboWindowSeconds: 5,
    curtainPrivacyDamage: 8,
    curtainBatteryDamage: 0.025,
  },
} as const;
