/** Gameplay tuning. Distances are Three.js world units. */
export const GAME_CONFIG = {
  destination: { z: -1800, radius: 13, name: "MOM" },
  battery: {
    start: 1,
    drainPerSecond: 0.012,
    boostExtraDrainPerSecond: 0.022,
  },
  movement: {
    cruiseSpeed: 8.7,
    accelerateSpeed: 14.5,
    brakeSpeed: 3.8,
    boostSpeed: 23,
    speedResponse: 3.8,
    lateralSpeed: 13,
    lateralResponse: 7,
    lateralLimit: 15,
    verticalSpeed: 9,
    verticalResponse: 6,
    minAltitude: -7,
    maxAltitude: 12,
    collisionRadius: 0.65,
    bankAmount: 0.18,
  },
  camera: { baseFov: 70, boostFov: 79, followResponse: 3.8, lookAhead: 22 },
  world: {
    fogDensity: 0.00078,
    fixtureLightIntensity: 1050,
    fixtureLightDistance: 84,
    bloomStrength: 0.3,
    bloomMaxHeight: 240,
  },
  scan: { cooldown: 5 },
  course: { splitZ: -740, splitStart: -640, splitEnd: -860, visibleAhead: 260 },
  obstacles: {
    damageBattery: 0.045,
    damagePrivacy: 9,
    rotorSpeed: 0.48,
    rotorHalfWidth: 1.3,
  },
  scoring: { targetSeconds: 160, fastSeconds: 110, timeMultiplier: 50 },
  nodes: {
    trackerPrivacyDamage: 12,
    trackerBatteryDamage: 0.04,
    nearMissMargin: 4.2,
    boosterCharge: 0.08,
    publicPrivacyDamage: 12,
    relayBurstSpeed: 4.5,
    relayBurstSeconds: 1.8,
    boosterBurstSeconds: 2.4,
    publicBurstSpeed: 9,
    publicBurstSeconds: 7,
    tipComboWindowSeconds: 5,
    curtainPrivacyDamage: 8,
    curtainBatteryDamage: 0.025,
  },
} as const;
