import type { Language } from "@/store/settingsStore";

export const COPY = {
  en: {
    oneMessage: "ONE MESSAGE LEFT",
    subtitle: "Reach the receiver before the signal dies.",
    transmit: "TRANSMIT",
    controls: "CONTROLS",
    settings: "SETTINGS",
    credits: "CREDITS",
    profile: "PROFILE",
    best: "BEST",
    stage: "STAGE",
    selectStage: "SELECT A CHANNEL",
    playerProfile: "OPERATOR PROFILE",
    profileIntro: "Give the final message a sender.",
    displayName: "DISPLAY NAME",
    xUsername: "X USERNAME · OPTIONAL",
    photoLink: "PROFILE PHOTO LINK · OPTIONAL",
    photoHint:
      "Paste an HTTPS image link. If it cannot be used on the card, your initials will appear.",
    saveProfile: "SAVE PROFILE",
    nameError: "Enter a name with at least 2 characters.",
    handleError:
      "Use only letters, numbers, or underscores for your X username.",
    urlError: "Use an HTTPS image link.",
    close: "CLOSE",
    language: "LANGUAGE",
    languageIntro: "Choose the language for the game interface.",
    incoming: "INCOMING",
    from: "FROM",
    powerRemaining: "POWER REMAINING",
    mainMenu: "MAIN MENU",
    battery: "BATTERY",
    privacy: "PRIVACY",
    safe: "SAFE",
    fast: "FAST",
    private: "100% PRIVATE",
    lowPower: "LOW POWER",
    scanReady: "SPACE · SCAN",
    boosting: "BOOSTING",
    paused: "PAUSED",
    pauseDetail: "Your signal is held. The battery will wait.",
    resume: "RESUME",
    restart: "RESTART TRANSMISSION",
    returnMenu: "RETURN TO MAIN MENU",
    delivered: "MESSAGE DELIVERED.",
    lost: "SIGNAL LOST.",
    reached: "Your message reached",
    depleted: "Battery depleted",
    awayFrom: "m from",
    score: "SCORE",
    time: "TIME",
    trackers: "COLLISIONS",
    retry: "RETRY",
    downloadCard: "DOWNLOAD CARD",
    newMessage: "NEW MESSAGE",
    copyResult: "COPY RESULT",
    copied: "COPIED TO CLIPBOARD",
    copyUnavailable: "COPY UNAVAILABLE",
    cardReady: "DOWNLOAD PNG",
    cardBack: "BACK TO RESULTS",
    cardTitle: "Your run, on record.",
    cardDetail:
      "A 1080 × 1350 PNG of your actual result, with Dlicom and Dili.",
    cardPreparing: "PREPARING YOUR TRANSMISSION CARD…",
    cardError: "CARD ART FAILED TO LOAD. PLEASE TRY AGAIN.",
    initializing: "INITIALIZING NETWORK...",
    skipIntro: "SKIP INTRO",
    encrypting: "ENCRYPTING MESSAGE...",
    routeReady: "ROUTE ESTABLISHED",
    newBest: "NEW PERSONAL BEST",
    audio: "AUDIO",
    visualControl: "VISUAL / CONTROL",
    masterVolume: "Master volume",
    musicVolume: "Music volume",
    sfxVolume: "SFX volume",
    mute: "Mute",
    cameraShake: "Camera shake",
    screenEffects: "Screen effects",
    reducedMotion: "Reduced motion",
    mouseInfluence: "Mouse influence",
    quality: "Quality",
    mobileLow: "Mobile capped at Low",
    fullscreen: "ENTER FULLSCREEN",
    exitFullscreen: "EXIT FULLSCREEN",
    replayGuide: "REPLAY GUIDE",
    powerStable: "TRANSMISSION HELD / POWER STABLE",
    guide: "FIELD GUIDE",
    next: "NEXT",
    understood: "UNDERSTOOD",
    cardSaved: "PNG SAVED",
    cardUnavailable: "DOWNLOAD UNAVAILABLE",
  },
  id: {
    oneMessage: "SATU PESAN TERSISA",
    subtitle: "Capai penerima sebelum sinyal padam.",
    transmit: "KIRIM PESAN",
    controls: "KONTROL",
    settings: "PENGATURAN",
    credits: "KREDIT",
    profile: "PROFIL",
    best: "TERBAIK",
    stage: "TAHAP",
    selectStage: "PILIH JALUR",
    playerProfile: "PROFIL OPERATOR",
    profileIntro: "Berikan identitas pada pesan terakhir ini.",
    displayName: "NAMA TAMPILAN",
    xUsername: "USERNAME X · OPSIONAL",
    photoLink: "LINK FOTO PROFIL · OPSIONAL",
    photoHint:
      "Tempel link gambar HTTPS. Jika tidak dapat dipakai di kartu, inisialmu akan tampil.",
    saveProfile: "SIMPAN PROFIL",
    nameError: "Masukkan nama minimal 2 karakter.",
    handleError:
      "Username X hanya boleh berisi huruf, angka, atau garis bawah.",
    urlError: "Gunakan link gambar HTTPS.",
    close: "TUTUP",
    language: "BAHASA",
    languageIntro: "Pilih bahasa antarmuka game.",
    incoming: "PESAN MASUK",
    from: "DARI",
    powerRemaining: "DAYA TERSISA",
    mainMenu: "MENU UTAMA",
    battery: "BATERAI",
    privacy: "PRIVASI",
    safe: "AMAN",
    fast: "CEPAT",
    private: "100% PRIVAT",
    lowPower: "DAYA KRITIS",
    scanReady: "SPASI · PINDAI",
    boosting: "AKSELERASI",
    paused: "JEDA",
    pauseDetail: "Sinyal berhenti sementara. Baterai tidak berkurang.",
    resume: "LANJUT",
    restart: "ULANGI TRANSMISI",
    returnMenu: "KEMBALI KE MENU",
    delivered: "PESAN TERKIRIM.",
    lost: "SINYAL HILANG.",
    reached: "Pesanmu sampai ke",
    depleted: "Baterai habis",
    awayFrom: "m dari",
    score: "SKOR",
    time: "WAKTU",
    trackers: "BENTURAN",
    retry: "COBA LAGI",
    downloadCard: "UNDUH KARTU",
    newMessage: "PESAN BARU",
    copyResult: "SALIN HASIL",
    copied: "TERSALIN",
    copyUnavailable: "TIDAK BISA MENYALIN",
    cardReady: "UNDUH PNG",
    cardBack: "KEMBALI KE HASIL",
    cardTitle: "Hasilmu, tercatat.",
    cardDetail: "PNG 1080 × 1350 berisi hasil permainanmu, Dlicom, dan Dili.",
    cardPreparing: "MENYIAPKAN KARTU HASIL…",
    cardError: "GAMBAR KARTU GAGAL DIMUAT. COBA LAGI.",
    initializing: "MENYIAPKAN JARINGAN...",
    skipIntro: "LEWATI INTRO",
    encrypting: "MENGENKRIPSI PESAN...",
    routeReady: "JALUR TERHUBUNG",
    newBest: "REKOR PRIBADI BARU",
    audio: "AUDIO",
    visualControl: "VISUAL / KONTROL",
    masterVolume: "Volume utama",
    musicVolume: "Volume musik",
    sfxVolume: "Volume efek",
    mute: "Senyap",
    cameraShake: "Guncangan kamera",
    screenEffects: "Efek layar",
    reducedMotion: "Kurangi gerakan",
    mouseInfluence: "Pengaruh mouse",
    quality: "Kualitas",
    mobileLow: "Ponsel dibatasi ke Low",
    fullscreen: "LAYAR PENUH",
    exitFullscreen: "KELUAR LAYAR PENUH",
    replayGuide: "ULANGI PANDUAN",
    powerStable: "TRANSMISI DIJEDA / DAYA STABIL",
    guide: "PANDUAN",
    next: "LANJUT",
    understood: "MENGERTI",
    cardSaved: "PNG TERSIMPAN",
    cardUnavailable: "GAGAL MENGUNDUH",
  },
} as const;

export function copyFor(language: Language) {
  return COPY[language];
}
